name: CI

on: [push]

jobs:
  start-release:
    runs-on: ubuntu-latest

    outputs:
      release-version: ${{ steps.start-release.outputs.release-version }}

    steps:
      - uses: actions/checkout@v4

      - name: run semantic-release
        id: start-release
        run: echo "release-version=1.2.3" >> $GITHUB_OUTPUT
        # run: echo "no release"

  # ------------------------------------------------------------------------------------------------

  setup-parallel-jobs:
    needs: start-release

    if: ${{ needs.start-release.outputs.release-version != '' }}

    runs-on: ubuntu-latest

    outputs:
      parallel-jobs: ${{ steps.setup-parallel-jobs.outputs.parallel-jobs }}

    steps:
      - uses: actions/checkout@v4

      - name: setup parallel jobs
        id: setup-parallel-jobs
        run: echo "parallel-jobs=$(bash scripts/setup-parallel-jobs.sh)" >> $GITHUB_OUTPUT

  # ------------------------------------------------------------------------------------------------

  run-job:
    needs: [start-release, setup-parallel-jobs]

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.setup-parallel-jobs.outputs.parallel-jobs) }}

    steps:
      - uses: actions/checkout@v4

      - name: run job ${{ matrix.id }}
        run: |
          bash scripts/run-job.sh \
            --id ${{ matrix.id }} \
            --version ${{ needs.start-release.outputs.release-version }}

  # ------------------------------------------------------------------------------------------------

  finish-release:
    needs: run-job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
