name: CI

on: [push, pull_request]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          # MATRIX_PARAMS_COMBINATIONS='{"include":[{"foo":"foo - 1","bar":"bar - 1"}]}'
          MATRIX_PARAMS_COMBINATIONS=$(bash scripts/generate-matrix-jobs.sh)
          echo $MATRIX_PARAMS_COMBINATIONS
          echo "::set-output name=matrix-combinations::$MATRIX_PARAMS_COMBINATIONS"
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}
          echo ${{ needs.setup-matrix.outputs.matrix-combinations }}
          echo ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
