name: CI

on: [push, pull_request]

jobs:
  _1st-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        run: bash generate-matrix-jobs.sh

  setup-matrix:
    runs-on: ubuntu-latest
    needs: _1st-job
    steps:
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          bash generate-matrix-jobs.sh
          MATRIX_PARAMS_COMBINATIONS=$(bash ./scripts/generate-matrix-jobs.sh)
          echo ::set-output name=matrix-combinations::{$MATRIX_PARAMS_COMBINATIONS}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}
          echo ${{ needs.setup-matrix.outputs.matrix-combinations }}
          echo ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
