name: CI

on: [push]

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  setup-parallel-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup-parallel-jobs
        run: echo "parallel-jobs=$(bash scripts/generate-matrix-jobs.sh)" >> $GITHUB_OUTPUT

      - run: |
          echo $GITHUB_OUTPUT

    outputs:
      parallel-jobs: ${{ steps.setup-parallel-jobs.outputs.parallel-jobs }}

  run-job:
    needs: setup-parallel-jobs
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.setup-parallel-jobs.outputs.parallel-jobs) }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo ${{ matrix.id }}
          echo $GITHUB_OUTPUT

  finish-release:
    needs: run-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
