name: CI

on: [push]

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  setup-parallel-jobs:
    needs: start-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: setup-parallel-jobs
        run: echo "parallel-jobs=$(bash scripts/setup-parallel-jobs.sh)" >> $GITHUB_OUTPUT

    outputs:
      parallel-jobs: ${{ steps.setup-parallel-jobs.outputs.parallel-jobs }}

  run-job:
    needs: setup-parallel-jobs
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.setup-parallel-jobs.outputs.parallel-jobs) }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "RELEASE_VERSION=${{ matrix.id }}" >> $GITHUB_ENV
          echo "RELEASE_JOB_ID=${{ matrix.id }}" >> $GITHUB_ENV

      - run: |
          bash scripts/run-job.sh ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_JOB_ID }}

  finish-release:
    needs: run-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
