name: CI

on: [push, pull_request]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup matrix combinations
        id: setup-matrix-jobs
        run: |
          MATRIX_JOBS=$(bash scripts/generate-matrix-jobs.sh)
          echo "matrix-jobs=$MATRIX_JOBS" >> $GITHUB_OUTPUT

    outputs:
      matrix-jobs: ${{ steps.setup-matrix-jobs.outputs.matrix-jobs }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix

    strategy:
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix-jobs) }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo ${{ matrix.id }}
          # echo foo=${{ matrix.foo }}
          # echo bar=${{ matrix.bar }}
          echo ${{ needs.setup-matrix.outputs.matrix-jobs }}
          # echo ${{ fromJson(needs.setup-matrix.outputs.matrix-jobs) }}
